//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenFlowers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_Introduce
    {
        public string ID { get; set; }
        public string ContentIntroduce { get; set; }
        public string Avatar { get; set; }
    }
}
