//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenFlowers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GF_Session
    {
        public int ID { get; set; }
        public string ID_Order { get; set; }
        public string ID_Session { get; set; }
        public string ID_Information { get; set; }
    }
}
